# sviluppo l'algoritmo per filtrare le parole
import re

# TODO: connect with a mysql db

if __name__ == '__main__':
    words_list = ['abito',
                  'aceto',
                  'acida',
                  'acido',
                  'acqua',
                  'acuto',
                  'addio',
                  'aereo',
                  'agile',
                  'agire',
                  'aglio',
                  'aiuto',
                  'album',
                  'alcol',
                  'alice',
                  'alito',
                  'altro',
                  'amare',
                  'amaro',
                  'ambra',
                  'amico',
                  'amore',
                  'ampio',
                  'anche',
                  'anima',
                  'ansia',
                  'apice',
                  'arena',
                  'aroma',
                  'asino',
                  'atrio',
                  'audio',
                  'avere',
                  'avuto',
                  'avvio',
                  'bacio',
                  'bagno',
                  'banca',
                  'banda',
                  'barca',
                  'basso',
                  'bello',
                  'benna',
                  'birra',
                  'bocca',
                  'bolla',
                  'bollo',
                  'bomba',
                  'bonus',
                  'bordo',
                  'borsa',
                  'bosco',
                  'bozza',
                  'brace',
                  'bravo',
                  'breve',
                  'buono',
                  'burro',
                  'busta',
                  'cagna',
                  'caldo',
                  'calma',
                  'campo',
                  'canto',
                  'capra',
                  'carne',
                  'carro',
                  'carta',
                  'carte',
                  'casco',
                  'causa',
                  'cenno',
                  'certo',
                  'cervo',
                  'ciclo',
                  'cieco',
                  'cielo',
                  'cigno',
                  'circa',
                  'circo',
                  'clima',
                  'cobra',
                  'collo',
                  'colpa',
                  'colpo',
                  'comma',
                  'conto',
                  'copia',
                  'coppa',
                  'corda',
                  'corno',
                  'corpo',
                  'corsa',
                  'corso',
                  'costa',
                  'costo',
                  'crema',
                  'crepa',
                  'crisi',
                  'croce',
                  'crudo',
                  'cuore',
                  'curva',
                  'danno',
                  'danza',
                  'degno',
                  'denso',
                  'dente',
                  'denti',
                  'dieci',
                  'dieta',
                  'disco',
                  'ditta',
                  'dolce',
                  'donna',
                  'drago',
                  'droga',
                  'entro',
                  'epoca',
                  'esame',
                  'esito',
                  'etica',
                  'etico',
                  'extra',
                  'falco',
                  'falso',
                  'fango',
                  'farro',
                  'fatto',
                  'felpa',
                  'fermo',
                  'ferro',
                  'festa',
                  'fetta',
                  'fiato',
                  'fibra',
                  'fieno',
                  'fiera',
                  'fiero',
                  'figli',
                  'finto',
                  'fiore',
                  'firma',
                  'fissa',
                  'fisso',
                  'fiume',
                  'folla',
                  'fondo',
                  'fonte',
                  'forma',
                  'forno',
                  'forse',
                  'forte',
                  'forum',
                  'forza',
                  'fossa',
                  'frase',
                  'frigo',
                  'frode',
                  'fuoco',
                  'fuori',
                  'furto',
                  'gamba',
                  'gamma',
                  'gatto',
                  'genio',
                  'gente',
                  'gesto',
                  'gioco',
                  'gioia',
                  'globo',
                  'gocce',
                  'golfo',
                  'gomma',
                  'gonna',
                  'grado',
                  'grano',
                  'grato',
                  'grave',
                  'greco',
                  'grido',
                  'guida',
                  'gusto',
                  'icona',
                  'invia',
                  'invio',
                  'isola',
                  'ladro',
                  'larga',
                  'largo',
                  'latte',
                  'leale',
                  'legge',
                  'legna',
                  'legno',
                  'lente',
                  'lento',
                  'leone',
                  'letto',
                  'libro',
                  'liceo',
                  'lieta',
                  'lieto',
                  'lieve',
                  'linea',
                  'lotta',
                  'lucci',
                  'lungo',
                  'luogo',
                  'lusso',
                  'madre',
                  'magia',
                  'magro',
                  'mamma',
                  'manzo',
                  'marca',
                  'marea',
                  'marmo',
                  'marzo',
                  'massa',
                  'matto',
                  'mazza',
                  'mazzo',
                  'media',
                  'medio',
                  'mensa',
                  'menta',
                  'mente',
                  'mento',
                  'merce',
                  'meteo',
                  'metro',
                  'mezzo',
                  'miele',
                  'mille',
                  'misto',
                  'molte',
                  'molti',
                  'molto',
                  'mondo',
                  'monte',
                  'morso',
                  'morte',
                  'morto',
                  'mucca',
                  'muffa',
                  'museo',
                  'mutuo',
                  'nervo',
                  'nonna',
                  'nonno',
                  'norma',
                  'notte',
                  'nozze',
                  'nulla',
                  'nuora',
                  'nuoto',
                  'nuovo',
                  'odore',
                  'oliva',
                  'oltre',
                  'ombra',
                  'onore',
                  'opera',
                  'osare',
                  'ovest',
                  'ovvio',
                  'padre',
                  'paese',
                  'palma',
                  'panca',
                  'panna',
                  'panne',
                  'panno',
                  'parco',
                  'parte',
                  'passo',
                  'pasta',
                  'pasto',
                  'paura',
                  'pausa',
                  'pazzo',
                  'pelle',
                  'penna',
                  'pesca',
                  'pesce',
                  'petto',
                  'pezzo',
                  'piace',
                  'piano',
                  'picco',
                  'piede',
                  'piega',
                  'pieno',
                  'pigro',
                  'pinza',
                  'pista',
                  'piuma',
                  'pizza',
                  'pochi',
                  'poeta',
                  'pollo',
                  'polpa',
                  'polso',
                  'pompa',
                  'ponte',
                  'porro',
                  'porta',
                  'porto',
                  'posta',
                  'posto',
                  'prato',
                  'preda',
                  'presa',
                  'prete',
                  'prima',
                  'primo',
                  'prova',
                  'punta',
                  'punto',
                  'quale',
                  'quasi',
                  'quota',
                  'radio',
                  'ragno',
                  'rango',
                  'ratto',
                  'razzo',
                  'reale',
                  'reato',
                  'regia',
                  'regno',
                  'resto',
                  'ricco',
                  'rissa',
                  'ritmo',
                  'robot',
                  'rogna',
                  'rosso',
                  'ruolo',
                  'ruota',
                  'russo',
                  'sacco',
                  'sacro',
                  'saldi',
                  'saldo',
                  'salsa',
                  'salta',
                  'salto',
                  'salva',
                  'salve',
                  'sanno',
                  'santa',
                  'santo',
                  'sasso',
                  'sauna',
                  'scala',
                  'scena',
                  'scopo',
                  'scudo',
                  'scusa',
                  'scuse',
                  'sedia',
                  'segno',
                  'senso',
                  'senza',
                  'serie',
                  'serio',
                  'sesto',
                  'setta',
                  'sette',
                  'sfera',
                  'sfida',
                  'socio',
                  'sodio',
                  'sogno',
                  'somma',
                  'sonno',
                  'sopra',
                  'sorso',
                  'sosia',
                  'sosta',
                  'sotto',
                  'spada',
                  'sparo',
                  'spesa',
                  'spese',
                  'sport',
                  'sposa',
                  'sputo',
                  'stand',
                  'stare',
                  'stato',
                  'stelo',
                  'stile',
                  'stima',
                  'succo',
                  'suino',
                  'suite',
                  'suola',
                  'suolo',
                  'suono',
                  'super',
                  'svago',
                  'tacco',
                  'talpa',
                  'tanto',
                  'tardi',
                  'tasca',
                  'tassa',
                  'tatto',
                  'tazza',
                  'tempo',
                  'tenda',
                  'tende',
                  'terra',
                  'terzo',
                  'testa',
                  'testo',
                  'tetto',
                  'tigre',
                  'tocco',
                  'torre',
                  'torta',
                  'torto',
                  'trama',
                  'trave',
                  'treno',
                  'trono',
                  'tutti',
                  'tutto',
                  'udire',
                  'udito',
                  'ulivo',
                  'umano',
                  'umore',
                  'unico',
                  'unire',
                  'unito',
                  'usare',
                  'usato',
                  'utile',
                  'valle',
                  'vario',
                  'vasto',
                  'venti',
                  'vento',
                  'verde',
                  'verso',
                  'vespa',
                  'vetro',
                  'video',
                  'villa',
                  'viola',
                  'virus',
                  'vista',
                  'volpe',
                  'volta',
                  'volto',
                  'vuoto',
                  'zaino',
                  'zampa',
                  'zebra',
                  'zitto',
                  'zucca',
                  'zuppa']

    # TODO: definire delle funzioni per testare il corretto inserimento da parte dell'utente. Va testasta la lunghezza delle stringhe, inoltre le stringhe devono essere composte solo da lettere(maiuscole o minuscole) e non devono essere presenti caratteri speciali

    print('Inserisci 5 caratteri per volta.\n Separa gli spazi vuoti usando il carattere "_".\n Non usare numeri o altri caratteri speciali.\n Ogni parola deve avere esattamente 5 caratteri.\n')
    absent_letter = input('Inserisci lettere assenti: ').replace("_", ".")
    while(len(absent_letter) != 5):
        print('Numero di caratteri errato! Inserire nuovamente la stringa')
        absent_letter = input('Inserisci lettere assenti: ').replace("_", ".")


    # TODO: add check for letter in random position

    letter_random_pos = input('Inserisci lettere presenti in posizione random ').replace("_", ".")
    while (len(letter_random_pos) != 5):
        print('Numero di caratteri errato! Inserire nuovamente la stringa')
        letter_random_pos = input('Inserisci lettere assenti: ').replace("_", ".")

    letter_random_pos_re = f'[{letter_random_pos.replace(".", "")}]'


    letter_def_pos = input('Inserisci lettere presenti in posizione definita: ').replace("_", ".")
    while (len(letter_def_pos) != 5):
        print('Numero di caratteri errato! Inserire nuovamente la stringa')
        letter_def_pos = input('Inserisci presenti in posizione definita: ').replace("_", ".")

    # print(f'Le stringhe inserite sono:\n - {absent_letter}\n - {letter_random_pos}\n - {letter_def_pos}')

    print(words_list)
    print(len(words_list))

    # Uso https://stackoverflow.com/questions/529424/traverse-a-list-in-reverse-order-in-python
    # Per leggere la lista al contrario
    for i in range(len(words_list)-1, -1, -1):
        if bool(re.match(absent_letter, words_list[i])) and absent_letter != '.....':
            print(f'Rimuovo: {words_list[i]}')
            words_list.remove(words_list[i])
        elif bool(re.match(letter_random_pos, words_list[i])) and letter_random_pos != '.....':
            print(f'Rimuovo: {words_list[i]}')
            words_list.remove(words_list[i])
        elif bool(re.match(letter_random_pos_re, words_list[i])):
            print(f'Rimuovo: {words_list[i]}')
            words_list.remove(words_list[i])
        elif not bool(re.match(letter_def_pos, words_list[i])):
            print(f'Rimuovo: {words_list[i]}')
            words_list.remove(words_list[i])




    print(words_list)
    print(len(words_list))



